/**
 * Pre-built theme combinations — apply all colors in one click.
 * Keys match DB setting_key (theme category).
 */

export const THEME_COLOR_GROUPS = [
  {
    id: 'brand',
    label: 'Brand colors',
    hint: 'Admin sidebar, footer, logo badge, nav highlights',
    keys: ['primary', 'secondary', 'accent', 'primary_hover', 'secondary_hover'],
  },
  {
    id: 'layout',
    label: 'Layout colors',
    hint: 'Page background, cards, header, body text, borders',
    keys: ['bg', 'surface', 'text', 'text_muted', 'border'],
  },
  {
    id: 'status',
    label: 'Status colors',
    hint: 'Order badges, success/error messages, alerts',
    keys: [
      'success', 'warning', 'danger',
      'success_bg', 'success_text',
      'warning_bg', 'warning_text',
      'danger_bg', 'danger_text',
      'info_bg', 'info_text',
    ],
  },
  {
    id: 'other',
    label: 'Other',
    hint: 'Border radius and font',
    keys: ['radius', 'font_family'],
  },
];

export const THEME_PRESETS = [
  {
    id: 'classic',
    name: 'Winvel Classic',
    description: 'Navy + coral — default store look',
    swatch: ['#1a1a2e', '#e94560', '#f8f9fa'],
    colors: {
      primary: '#1a1a2e',
      secondary: '#e94560',
      accent: '#0f3460',
      bg: '#f8f9fa',
      surface: '#ffffff',
      text: '#1a1a2e',
      text_muted: '#6c757d',
      border: '#dee2e6',
      success: '#28a745',
      warning: '#ffc107',
      danger: '#dc3545',
      primary_hover: '#2a2a4e',
      secondary_hover: '#d63851',
      success_bg: '#d4edda',
      success_text: '#155724',
      warning_bg: '#fff3cd',
      warning_text: '#856404',
      danger_bg: '#f8d7da',
      danger_text: '#721c24',
      info_bg: '#d1ecf1',
      info_text: '#0c5460',
      radius: '8px',
      font_family: 'Inter, system-ui, sans-serif',
    },
  },
  {
    id: 'ocean',
    name: 'Ocean Blue',
    description: 'Cool blues — clean and professional',
    swatch: ['#0c4a6e', '#0284c7', '#f0f9ff'],
    colors: {
      primary: '#0c4a6e',
      secondary: '#0284c7',
      accent: '#0369a1',
      bg: '#f0f9ff',
      surface: '#ffffff',
      text: '#0c4a6e',
      text_muted: '#64748b',
      border: '#bae6fd',
      success: '#059669',
      warning: '#d97706',
      danger: '#dc2626',
      primary_hover: '#075985',
      secondary_hover: '#0369a1',
      success_bg: '#d1fae5',
      success_text: '#065f46',
      warning_bg: '#fef3c7',
      warning_text: '#92400e',
      danger_bg: '#fee2e2',
      danger_text: '#991b1b',
      info_bg: '#e0f2fe',
      info_text: '#0c4a6e',
      radius: '8px',
      font_family: 'Inter, system-ui, sans-serif',
    },
  },
  {
    id: 'sunset',
    name: 'Sunset Warm',
    description: 'Warm orange & amber — energetic feel',
    swatch: ['#7c2d12', '#ea580c', '#fff7ed'],
    colors: {
      primary: '#7c2d12',
      secondary: '#ea580c',
      accent: '#c2410c',
      bg: '#fff7ed',
      surface: '#ffffff',
      text: '#431407',
      text_muted: '#9a3412',
      border: '#fed7aa',
      success: '#16a34a',
      warning: '#ca8a04',
      danger: '#dc2626',
      primary_hover: '#9a3412',
      secondary_hover: '#c2410c',
      success_bg: '#dcfce7',
      success_text: '#166534',
      warning_bg: '#fef9c3',
      warning_text: '#854d0e',
      danger_bg: '#fee2e2',
      danger_text: '#991b1b',
      info_bg: '#ffedd5',
      info_text: '#9a3412',
      radius: '10px',
      font_family: 'Inter, system-ui, sans-serif',
    },
  },
  {
    id: 'forest',
    name: 'Forest Green',
    description: 'Earth greens — natural and calm',
    swatch: ['#14532d', '#16a34a', '#f0fdf4'],
    colors: {
      primary: '#14532d',
      secondary: '#16a34a',
      accent: '#166534',
      bg: '#f0fdf4',
      surface: '#ffffff',
      text: '#14532d',
      text_muted: '#4b5563',
      border: '#bbf7d0',
      success: '#15803d',
      warning: '#ca8a04',
      danger: '#dc2626',
      primary_hover: '#166534',
      secondary_hover: '#15803d',
      success_bg: '#dcfce7',
      success_text: '#14532d',
      warning_bg: '#fef9c3',
      warning_text: '#854d0e',
      danger_bg: '#fee2e2',
      danger_text: '#991b1b',
      info_bg: '#d1fae5',
      info_text: '#065f46',
      radius: '8px',
      font_family: 'Inter, system-ui, sans-serif',
    },
  },
  {
    id: 'royal',
    name: 'Royal Purple',
    description: 'Purple & violet — bold and modern',
    swatch: ['#4c1d95', '#7c3aed', '#f5f3ff'],
    colors: {
      primary: '#4c1d95',
      secondary: '#7c3aed',
      accent: '#5b21b6',
      bg: '#f5f3ff',
      surface: '#ffffff',
      text: '#3b0764',
      text_muted: '#6b7280',
      border: '#ddd6fe',
      success: '#059669',
      warning: '#d97706',
      danger: '#dc2626',
      primary_hover: '#5b21b6',
      secondary_hover: '#6d28d9',
      success_bg: '#d1fae5',
      success_text: '#065f46',
      warning_bg: '#fef3c7',
      warning_text: '#92400e',
      danger_bg: '#fee2e2',
      danger_text: '#991b1b',
      info_bg: '#ede9fe',
      info_text: '#5b21b6',
      radius: '12px',
      font_family: 'Inter, system-ui, sans-serif',
    },
  },
  {
    id: 'midnight',
    name: 'Midnight Dark',
    description: 'Dark mode — easy on the eyes',
    swatch: ['#0f172a', '#38bdf8', '#1e293b'],
    colors: {
      primary: '#0f172a',
      secondary: '#38bdf8',
      accent: '#1e3a5f',
      bg: '#0f172a',
      surface: '#1e293b',
      text: '#f1f5f9',
      text_muted: '#94a3b8',
      border: '#334155',
      success: '#34d399',
      warning: '#fbbf24',
      danger: '#f87171',
      primary_hover: '#1e293b',
      secondary_hover: '#0ea5e9',
      success_bg: '#064e3b',
      success_text: '#a7f3d0',
      warning_bg: '#78350f',
      warning_text: '#fde68a',
      danger_bg: '#7f1d1d',
      danger_text: '#fecaca',
      info_bg: '#1e3a5f',
      info_text: '#bae6fd',
      radius: '8px',
      font_family: 'Inter, system-ui, sans-serif',
    },
  },
  {
    id: 'minimal',
    name: 'Minimal Mono',
    description: 'Black, white & gray — timeless minimal',
    swatch: ['#18181b', '#18181b', '#fafafa'],
    colors: {
      primary: '#18181b',
      secondary: '#18181b',
      accent: '#3f3f46',
      bg: '#fafafa',
      surface: '#ffffff',
      text: '#18181b',
      text_muted: '#71717a',
      border: '#e4e4e7',
      success: '#22c55e',
      warning: '#eab308',
      danger: '#ef4444',
      primary_hover: '#3f3f46',
      secondary_hover: '#3f3f46',
      success_bg: '#dcfce7',
      success_text: '#166534',
      warning_bg: '#fef9c3',
      warning_text: '#854d0e',
      danger_bg: '#fee2e2',
      danger_text: '#991b1b',
      info_bg: '#f4f4f5',
      info_text: '#3f3f46',
      radius: '4px',
      font_family: 'Inter, system-ui, sans-serif',
    },
  },
  {
    id: 'coral',
    name: 'Coral Pop',
    description: 'Bright coral & pink — playful youth brand',
    swatch: ['#be185d', '#f43f5e', '#fff1f2'],
    colors: {
      primary: '#be185d',
      secondary: '#f43f5e',
      accent: '#9d174d',
      bg: '#fff1f2',
      surface: '#ffffff',
      text: '#881337',
      text_muted: '#9f1239',
      border: '#fecdd3',
      success: '#10b981',
      warning: '#f59e0b',
      danger: '#ef4444',
      primary_hover: '#9d174d',
      secondary_hover: '#e11d48',
      success_bg: '#d1fae5',
      success_text: '#065f46',
      warning_bg: '#fef3c7',
      warning_text: '#92400e',
      danger_bg: '#fee2e2',
      danger_text: '#991b1b',
      info_bg: '#ffe4e6',
      info_text: '#9d174d',
      radius: '16px',
      font_family: 'Inter, system-ui, sans-serif',
    },
  },
];

export function presetToFormValues(preset) {
  const values = {};
  for (const [key, value] of Object.entries(preset.colors)) {
    values[`theme.${key}`] = value;
  }
  return values;
}

export function presetToUpdates(preset) {
  return Object.entries(preset.colors).map(([settingKey, settingValue]) => ({
    category: 'theme',
    settingKey,
    settingValue,
  }));
}

export function detectActivePreset(formValues) {
  for (const preset of THEME_PRESETS) {
    const match = Object.entries(preset.colors).every(
      ([key, value]) => formValues[`theme.${key}`] === value
    );
    if (match) return preset.id;
  }
  return null;
}
